# -*- coding: utf-8 -*-
"""
Created on Wed May 20 23:33:23 2015

@author: Daniel Dixey
"""

################# Algorithm #################

print('Importing Modules\n')
# Import Modules
from pyteaser import SummarizeUrl

print('Adding Websites\n')
# Add random articles
Urls = {'Huffington': 'http://www.huffingtonpost.com/2013/11/22/twitter-forward-secrecy_n_4326599.html'}
Urls.update({'BBC': 'http://www.bbc.co.uk/news/business-32817114'})
Urls.update({'BBC Tech': 'http://www.bbc.co.uk/news/technology-32814309'})
Urls.update({'BBC News': 'http://www.bbc.co.uk/news/uk-england-32822298'})

print('Summarising Websites\n\n')
# Loop through each site in the Dictionary
for Site in Urls:
    # Print the name of the Site in Use
    print('Website: %s') % (Site)
    # Use the SummarizeURL function
    summaries = SummarizeUrl(Urls[Site])
    # Print Each Sentence on a new line
    for sentence in summaries:
        print sentence
    print('\n')

################# Output #################

# Importing Modules
#
# Adding Websites
#
# Summarising Websites
#
# Website: BBC
# Separately, the Federal Reserve fined a sixth bank, Bank of America, $205m over foreign exchange-rigging.
# The criminal fines of more than $2.5bn are the largest set of anti-trust fines obtained by the Department of Justice.
# Five of the world's largest banks are to pay fines totalling $5.7bn (£3.6bn) for charges including manipulating the foreign exchange market.
# The £284m fine imposed on Barclays by Britain's Financial Conduct Authority was a record by the regulator.
#"No retroactive massive Libor fine for Barclays is a big positive, as is no reopening of the NPA (non-prosecution agreement).
#
#
# Website: BBC News
# Eight men have been charged with plotting the Hatton Garden jewellery heist, Scotland Yard has said.
#
#
# Thieves had used heavy cutting equipment to break into a vault at Hatton Garden Safe Deposit Ltd, where they ransacked about 70 boxes.
# Detectives from the Met's Flying Squad charged the men, aged between 48 and 76, with conspiracy to burgle on Wednesday evening.
# The full list of those charged:
#
# Two of the men charged are believed to be father and son.
# Brian Reader, 76, and Paul Reader, 50, were both arrested at an address in Dartford, Kent.
#
#
# Website: Huffington
# Twitter's move is the latest response from U.S. Internet firms following disclosures by former spy agency contractor Edward Snowden about widespread, classified U.S. government surveillance programs.
#"Since then, it has become clearer and clearer how important that step was to protecting our users' privacy."
# The online messaging service, which began scrambling communications in 2011 using traditional HTTPS encryption, said on Friday it has added an advanced layer of protection for HTTPS known as "forward secrecy."
#"A year and a half ago, Twitter was first served completely over HTTPS," the company said in a blog posting.
# "I'm glad this is the direction the industry is taking."
#
#(Reporting by Jim Finkle; editing by Andrew Hay)
#
#
# Website: BBC Tech
# Nevertheless, the fix that web-browser makers have agreed on is that their software should block 512-bit or weaker encryption keys.
# Web-browser makers are preparing a fix for a flaw in an encryption algorithm that makes it possible to spy on supposedly secure communications.
# A Diffie-Hellman key exchange was one of the first techniques developed to allow two or more parties to create and share an encryption key by exchanging parts of the key in public.
# The "LogJam attack" was discovered by researchers at Microsoft and a number of US and French universities.
# These limited the complexity of the secret encryption codes that could
# be generated by "international versions" of US-made software, including
# Netscape's web browser.
